server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.0.15.90:3100/loki/api/v1/push

scrape_configs:
- job_name: loki
  static_configs:
  - targets:
    - localhost
    labels:
      job: issuefylog
      __path__: /logs/**/*.log